[package]
name = "openrr-nav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32"
grid_map = "0.1"
arci = "0.1"
thiserror = "1"

[dev-dependencies]
rand = "0.8"
rrt = "0.7"
